<?php include($app->getComponentPath("header")); ?>



<section>

	<div class="container">
		<div class="row">
			<div class="col-10">
				<div class="col" style="text-align: center; padding-top: 15px;">
					<label class="titil">Add Subject Form </label>
					<hr style="color: crimson;  width: 100%;">
				</div>
				<div class="col-12">
					<div class="container">
						<form method="post">
							<?= isset($_GET['success']) ? '<div class="alert alert-success" role="alert">Thank you for Sign Up !</div>' : "" ?>
							<div class="form-row">
								<div class="col-md-6">
									<label for="validationServer01">Subject Name</label>
									<input type="text" class="form-control " id="validationServer01" name="name" required>
								
								</div>


								<div class="col-6">
									<label for="validationServer05">Stage</label>
									<select name="stage_id" class="custom-select" required>
										<option value="" disabled selected>choose stage</option>
										<?php
										foreach ($stages as $stage) {
											echo '<option value="' . $stage['id'] . '">' . $stage['name'] . '</option>';
										}
										?>


									</select>

								</div>

								<hr style="color: crimson;  width: 100%;">

								<div class="col" style="text-align: center; padding-top: 15px;">
									<button type="submit" style="width: 100%;" class="btn">Submit</button>
								</div>
							</div>
							<hr style="color: crimson;  width: 100%;">



						</form>
					</div>
				</div>

			</div>
		</div>
	</div>
	</div>
</section>

</section>

</footer>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<?php include($app->getComponentPath("footer")); ?>
</body>

</html>