
  <?php include($app->getComponentPath("header")); ?>




  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Mangear School</h1>
      <p class="lead">
        This is a modified jumbotron that occupies the entire horizontal space of its parent.

      </p>
    </div>
  </div>
  <section class="row">


    <div class="card col-md-3 shadow p-3 mb-5 bg-white rounded" style="width: 25rem;">
      <img src="./assets/img/first.jpg" class="card-img-top" alt="..." style="width: 100%;">
      <hr>
      <div class="card-body">
        <h5 class="card-title">First Stage</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go To</a>
      </div>
    </div>


    <div class="card col-md-3 shadow p-3 mb-5 bg-white rounded" style="width: 25rem;">
      <img src="./assets/img/Second.jpg" class="card-img-top" alt="..." style="width: 100%;">
      <hr>
      <div class="card-body">
        <h5 class="card-title">Second Stage</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go To</a>
      </div>
    </div>

    <div class="card col-md-3 shadow p-3 mb-5 bg-white rounded" style="width: 25rem;">
      <img src="./assets/img/third.jpg" class="card-img-top" alt="..." style="width: 100%;">
      <hr>
      <div class="card-body">
        <h5 class="card-title">Third Stage</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go To</a>
      </div>
    </div>

  </section>









  <footer class="footer">
    <div class="row">
      <div class="col">
        <p>Some quick example text to build on the card title and make up the bulk of the card's content.
          Some quick example text to build on the card title and make up the bulk of the card's content.
          Some quick example text to build on the card title and make up the bulk of the card's content.
          Some quick example text to build on the card title and make up the bulk of the card's content.
        </p>

        <ul>
          <a href="#">
            <li><img class="icon" src="./assets/img/facebook.png"></li>
          </a>
          <a href="#">
            <li><img class="icon" src="./assets/img/instagram.png"></li>
          </a>
          <a href="#">
            <li><img class="icon" src="./assets/img/wat.png"></li>
          </a>
          <a href="#">
            <li><img class="icon" src="./assets/img/twe.png"></li>
          </a>
          <a href="#">
            <li><img class="icon" src="./assets/img/p.png"></li>
          </a>

        </ul>
      </div>

      <div class="col">
        <div class="s-footer__copyright" style="margin-top: 30%; margin-bottom: 5%;">
          <span>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>
              document.write(new Date().getFullYear());
            </script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="" target="_blank">OLa</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </span>
        </div>
      </div>
    </div>
    </div>



  </footer>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <?php include($app->getComponentPath("footer"));?>
</body>

</html>