<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <?php include($app->getComponentPath("header")); ?>



  <style>
    @import url('https://fonts.googleapis.com/css?family=Pacifico&display=swap');
  </style>

  <title>School</title>
</head>

<body>
  <header>
    <h1 class="header">
      Manager School
    </h1>
  </header>


  <nav class="navbar navbar-expand-lg navbar-light  navbar navbar-light" style="background-color: rgb(76, 186, 223);">
    <a class="navbar-brand" href="#"><img src="./assets/img/sha.png" style="width: 45px; height: 45px; margin-right: 10px;">Manager School</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Techer</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Stage
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">First</a>
            <a class="dropdown-item" href="#">Second</a>

            <a class="dropdown-item" href="#">Third</a>

        </li>
        <li class="nav-item">
          <a class="nav-link" href="sign.html">Student</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Degree</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        <a href="?page=signup"><button class="btn btn-outline-success my-2 my-sm-0" type="submit">sign up</button></a>
        <a href="?page=login"><button class="btn btn-outline-success my-2 my-sm-0" type="submit">login</button></a>
      </form>
    </div>

  </nav>

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Mangear School</h1>
      <p class="lead">
        This is a modified jumbotron that occupies the entire horizontal space of its parent.

      </p>
    </div>
  </div>
  <section class="row">


    <div class="card col-md-3 shadow p-3 mb-5 bg-white rounded" style="width: 25rem;">
      <img src="./assets/img/first.jpg" class="card-img-top" alt="..." style="width: 100%;">
      <hr>
      <div class="card-body">
        <h5 class="card-title">First Stage</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go To</a>
      </div>
    </div>


    <div class="card col-md-3 shadow p-3 mb-5 bg-white rounded" style="width: 25rem;">
      <img src="./assets/img/Second.jpg" class="card-img-top" alt="..." style="width: 100%;">
      <hr>
      <div class="card-body">
        <h5 class="card-title">Second Stage</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go To</a>
      </div>
    </div>

    <div class="card col-md-3 shadow p-3 mb-5 bg-white rounded" style="width: 25rem;">
      <img src="./assets/img/third.jpg" class="card-img-top" alt="..." style="width: 100%;">
      <hr>
      <div class="card-body">
        <h5 class="card-title">Third Stage</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go To</a>
      </div>
    </div>

  </section>









  <footer class="footer">
    <div class="row">
      <div class="col">
        <p>Some quick example text to build on the card title and make up the bulk of the card's content.
          Some quick example text to build on the card title and make up the bulk of the card's content.
          Some quick example text to build on the card title and make up the bulk of the card's content.
          Some quick example text to build on the card title and make up the bulk of the card's content.
        </p>

        <ul>
          <a href="#">
            <li><img class="icon" src="./assets/img/facebook.png"></li>
          </a>
          <a href="#">
            <li><img class="icon" src="./assets/img/instagram.png"></li>
          </a>
          <a href="#">
            <li><img class="icon" src="./assets/img/wat.png"></li>
          </a>
          <a href="#">
            <li><img class="icon" src="./assets/img/twe.png"></li>
          </a>
          <a href="#">
            <li><img class="icon" src="./assets/img/p.png"></li>
          </a>

        </ul>
      </div>

      <div class="col">
        <div class="s-footer__copyright" style="margin-top: 30%; margin-bottom: 5%;">
          <span>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>
              document.write(new Date().getFullYear());
            </script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="" target="_blank">OLa</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </span>
        </div>
      </div>
    </div>
    </div>



  </footer>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <?php include($app->getComponentPath("footer"));?>
</body>

</html>