<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <?php include($app->getComponentPath("header")); ?>

    

    <style>
        @import url('https://fonts.googleapis.com/css?family=Pacifico&display=swap');
        </style>

    <title>School</title>
  </head>
  <body>
      <header>
          <h1 class="header">
              Manager School
          </h1>
      </header>
    

    <nav class="navbar navbar-expand-lg navbar-light  navbar navbar-light" style="background-color: rgb(76, 186, 223);">
        <a class="navbar-brand" href="?page=home"><img src="./assets/img/sha.png" style="width: 45px; height: 45px; margin-right: 10px;">Manager School</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="index.html" href="?page=home">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Techer</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Stage
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">First</a>
                <a class="dropdown-item" href="#">Second</a>
                
                <a class="dropdown-item" href="#">Third</a>
              
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Student</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Degree</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            <a href="sign up.html"><button class="btn btn-outline-success my-2 my-sm-0" type="submit">sign up</button></a>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">login</button>
          </form>
        </div>
        
      </nav>

      <section >
        
        <div class="container">
          <div class="row">
            <div class="col-10" >
              <div class="col" style="text-align: center; padding-top: 15px;">
              <label class="titil">Student Information Form </label>
              <hr style="color: crimson;  width: 100%;">
              </div>
              <form>
                <div class="form-row">
                  <div class="col-md-3">
                    <label for="validationServer01">First Name</label>
                    <input type="text" class="form-control is-valid" id="validationServer01" value="Ola" required>
                    <div class="valid-feedback">
                      Looks good!
                    </div>
                  </div>
                  <div class="col-md-3">
                    <label for="validationServer02"> Last Name</label>
                    <input type="text" class="form-control is-valid" id="validationServer02" value="Ali" required>
                    <div class="valid-feedback">
                      Looks good!
                    </div>
                  </div>
                  <div class="col-md-3">
                    <label for="validationServer03"> Third Name</label>
                    <input type="text" class="form-control is-valid" id="validationServer03" value="Abod" required>
                    <div class="valid-feedback">
                      Looks good!
                    </div>
                  </div>
                  <div class="col-md-3">
                    <label for="validationServer04">Nick Name</label>
                    <input type="text" class="form-control is-valid" id="validationServer04" value="Allll" required>
                    <div class="valid-feedback">
                      Looks good!
                    </div>
                    </div>
              <hr style="color: crimson;  width: 100%;">

                    <div class="col-6">
                        <label for="validationServer05">Stage</label>
                        <input type="text" class="form-control is-valid" id="validationServer05" value="first" required>
                        <div class="valid-feedback">
                          Looks good!
                        </div>
                      </div>
                      <div class="col-6">
                        <label for="validationServer06">Birth Day</label>
                        <input type="date" class="form-control is-valid" id="validationServer06" value="" required>
                        <div class="valid-feedback">
                          Looks good!
                        </div>
                      </div>
                      <hr style="color: crimson;  width: 100%;">

                    <div class="col-6">
                        <label for="validationServer07">E_mail</label>
                        <input type="" class="form-control is-valid" id="validationServer07" value="sbhs@gmail.com" required>
                        <div class="valid-feedback">
                          Looks good!
                        </div>
                      </div>
                      <div class="col-6">
                        <label for="validationServer08">PassWord</label>
                        <input type="password" class="form-control is-valid" id="validationServer08" value="" required>
                        <div class="valid-feedback">
                          Looks good!
                        </div>
                      </div>
                      <hr style="color: crimson;  width: 100%;">

                    <div class="col-6">
                        <label for="validationServer07">User Name</label>
                        <input type="" class="form-control is-valid" id="validationServer07" value="@Ola_IT" required>
                        <div class="valid-feedback">
                          Looks good!
                        </div>
                      </div>
                      <div class="col-6">
                        <label for="validationServer08">PassWord</label>
                        <input type="password" class="form-control is-valid" id="validationServer08" value="" required>
                        <div class="valid-feedback">
                          Looks good!
                        </div>
                      </div>
                      <hr style="color: crimson;  width: 100%;">
                      
                        <div class="col" style="text-align: center; padding-top: 15px;">
                      <button type="submit" style="width: 100%;" class="btn btn-danger">Submit</button>
                      </div>
                      </div>
                      <hr style="color: crimson;  width: 100%;">

                     
              </form>

              </div>
            </div>
          </div>
        </div>
            </section>
          
      </section>

      </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <?php include($app->getComponentPath("footer")); ?>
  </body>
</html>