<?php include($app->getComponentPath("header")); ?>



<section>

    <div class="container">
    <div class="card">
            <div class="card-body">
                <div class="card-title">Teachers</div>
                <div class="container">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Contact</th>
                                <th>Subject</th>
                                <th>
                                    <a href="?page=add_teacher">Add Teacher</a>
                                </th>
                              
                            </tr>
                        </thead>

                        <tbody>
                            <?php
                            foreach ($rows as $k => $v) {
                                echo "<tr>";
                                echo "<td>" . intval($k + 1)  . "</td>";
                                echo "<td>" . $v['name']  . "</td>";
                                echo "<td>" . $v['contact']  . "</td>";
                                echo "<td>" . $v['subject']  . "</td>";
                                echo "<td></td>";

                                echo "</tr>";
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<?php include($app->getComponentPath("footer")); ?>
</body>

</html>